### ISSUE TITLE
Create Learn Introduction Section

### ISSUE THREAD

**Issue by TheGreatAxios** [Dirt-Road-Development/shiny-octo-giggle#7]
```[tasklist]
### Tasks
- [x] About SKALE Network 📄
- [x] SKALE Chain Overview 📄
- [x] FAQ 📄
- [x] Mainnet Beta 📄
- [ ] FAQ - Update Items
```
